name: Automatic release

on:
  push:
    branches:
      - geokrety

jobs:
  build-release:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/release-with-docker.yml@main
    with:
      image_name: geokrety/osm-static-maps
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
